# Generated by Django 3.2.16 on 2023-02-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230221_0724'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_author_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='folloiwng',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'folloiwng'), name='unique_folloiwng_user'),
        ),
    ]
