# Generated by Django 3.2.16 on 2023-02-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230222_0656'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_folloiwng_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='folloiwng',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_following_user'),
        ),
    ]
